# Render Blueprint for EZSportsApp

services:
  - type: web
    name: ezsportsapp
    env: node
    plan: free
    rootDirectory: server
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: TRUST_PROXY
        value: "1"
      # Configure the following in the Render dashboard or override in this blueprint as needed:
      # - key: JWT_SECRET
      #   generateValue: true
      # - key: CORS_ORIGINS
      #   value: https://<your-service>.onrender.com
      # - key: STRIPE_SECRET_KEY
      #   sync: false
      # - key: STRIPE_WEBHOOK_SECRET
      #   sync: false
